---
    - name: Ensure Homebrew is installed
      homebrew:
        state: present

    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Install cowsay
      homebrew:
        name: cowsay
        state: present

    - name: Install fortune
      homebrew:
        name: fortune 
        state: present

    - name: Install chafa
      homebrew:
        name: chafa
        state: present

    - name: Clone pokemon-colorscripts repository
      git:
        repo: https://gitlab.com/phoneybadger/pokemon-colorscripts.git
        dest: "{{ package_dir }}/pokemon-colorscripts"

    - name: Run install.sh script
      command: ./install.sh
      become: true
      args:
        chdir: "{{ package_dir }}/pokemon-colorscripts"

