---
- name: Ensure curl is installed
  become: yes
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Check if NVM is already installed
  stat:
    path: ~/.nvm/nvm.sh
  register: nvm_installed

- name: Download and install NVM
  shell: |
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
  args:
    executable: /bin/bash
  when: not nvm_installed.stat.exists

- name: Source shell profile to load NVM
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
  when: not nvm_installed.stat.exists
