---
- name: Debug OS family
  ansible.builtin.debug:
    msg: "OS family is {{ ansible_os_family }}"

- block:
    - name: Ensure required packages are installed (Ubuntu)c
      apt:
        name:
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - build-essential
        state: present
  when: ansible_os_family == "Debian"

- block:
    - name: Ensure Xcode command line tools are installed (macOS)
      command: xcode-select --install
      args:
        creates: /Library/Developer/CommandLineTools

    - name: Ensure required packages are installed (macOS)
      become: no
      homebrew:
        name:
          - ninja
          - gettext
          - cmake
          - curl
        state: present
  when: ansible_os_family == "Darwin"

- name: Get home directory
  import_tasks: ../roles/common/hooks/get-home-directory.yaml

- name: Clone Neovim repository
  git:
    repo: "{{ neovim_repo }}"
    dest: "{{user_home_directory}}/{{ package_dir }}/neovim"
    version: master
    update: true
    force: true

- name: Build Neovim
  command:
    argv:
      - make
      - CMAKE_BUILD_TYPE=RelWithDebInfo
      - CMAKE_INSTALL_PREFIX={{ user_home_directory }}/{{ package_dir }}/neovim
  args:
    chdir: "{{user_home_directory}}/{{ package_dir }}/neovim"
  register: build_neovim
  retries: 2
  until: build_neovim is success

- name: Install Neovim
  become: true
  shell: |
    make install
  args:
    chdir: "{{user_home_directory}}/{{ package_dir }}/neovim"
