---
- name: Install Neovim Nightly
  hosts: all
  become: true
  vars:
    neovim_repo: "https://github.com/neovim/neovim.git"

  tasks:
    - name: Debug OS family
      ansible.builtin.debug:
        msg: "OS family is {{ ansible_os_family }}"

    - block:
        - name: Ensure required packages are installed (Ubuntu)c
          apt:
            name:
              - ninja-build
              - gettext
              - cmake
              - unzip
              - curl
              - build-essential
            state: present
      when: ansible_os_family == "Debian"

    - block:
        - name: Ensure Xcode command line tools are installed (macOS)
          command: xcode-select --install
          args:
            creates: /Library/Developer/CommandLineTools

        - name: Ensure required packages are installed (macOS)
          become: no
          homebrew:
            name:
              - ninja
              - gettext
              - cmake
              - curl
            state: present
      when: ansible_os_family == "Darwin"

    - name: Clone Neovim repository
      git:
        repo: "{{ neovim_repo }}"
        dest: "{{ package_dir }}/neovim"
        version: master
        force: yes

    - name: Build Neovim
      shell: |
        make CMAKE_BUILD_TYPE=RelWithDebInfo
      args:
        chdir: "{{ package_dir }}/neovim"
      register: build_neovim
      retries: 2
      until: build_neovim is success

    - name: Install Neovim
      shell: |
        make install
      args:
        chdir: "{{ package_dir }}/neovim"
