- name: Bootstrap development machines
  hosts: development
  roles:
    - role: mac
      when: ansible_facts['os_family'] == 'Darwin'
    - role: linux
      when: ansible_facts['os_family'] == 'Debian'
    - role: common
