- name: Bootstrap development machines
  hosts: development
  roles:
    - role: common/install-ascii
    - role: common/install-fuzzy-find
    - role: common/install-neovim
    - role: mac/install-apps
      when: ansible_facts['os_family'] == 'Darwin'
    - role: linux/install-apps
      when: ansible_facts['os_family'] != 'Darwin'

