- name: Bootstrap development machines
  hosts: development
  roles:
    - role: mac/install-apps
      when: ansible_facts['os_family'] == 'Darwin'
    - role: linux/install-apps
      when: ansible_facts['os_family'] == 'Debian'
    - role: common
