export DOTFILE_PATH="$HOME/.config/dch"
source "$DOTFILE_PATH/configs/bash/.vars"
source "$DOTFILE_PATH/configs/bash/.aliases"
source "$DOTFILE_PATH/configs/bash/.functions"
source "$DOTFILE_PATH/configs/bash/.bash"
