name: Deploy
on:
  push:
    branches: [ "primary" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        # Add runner names here
        runner: [ lab-01, runner2, runner3 ]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Testing...
          touch /home/derek/test-my-runner.log
